// <auto-generated />
using System;
using ApuntesDominoAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApuntesDominoAPI.Migrations
{
    [DbContext(typeof(apuntesdominodbContext))]
    [Migration("20230318205046_tema2")]
    partial class tema2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApuntesDominoAPI.Models.Tfondo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Defecto")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Fonnombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Fonpie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fonruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tfondos");
                });

            modelBuilder.Entity("ApuntesDominoAPI.Models.Timagene", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Idpatro")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Idtema")
                        .HasColumnType("tinyint");

                    b.Property<string>("Imgcomentcorto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgcomentlargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgnomimagevid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgruta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgtipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timagenes");
                });

            modelBuilder.Entity("ApuntesDominoAPI.Models.Tpatrocinadore", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Abreviapatro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccionpatro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Idpatro")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombrepatro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono1patro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2patro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tpatrocinadores");
                });

            modelBuilder.Entity("ApuntesDominoAPI.Models.Ttema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Defecto")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Temnombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Ttemas");
                });
#pragma warning restore 612, 618
        }
    }
}
